name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for posting your first issue! A developer from TPPS will look at this soon.'
        pr-message: 'Thanks for making your first PR! A developer from TPPS will look at this soon.'
