name: Apple Mac Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos # Specified version isn't needed for GH Actions

    steps:
    - uses: actions/checkout@v2
    env:
       HOMEBREW_NO_ANALYTICS: 1
    - name: Go to Linux folder
      run: cd binary/linux
    - name: Run configure
      run: ./configure
    - name: Compile
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
